### ISSUE TITLE
Hianime & Kaido extensions has an error and can't play episodes

### ISSUE THREAD

**Issue by CircleSideisCOOL** [almightyhak/aniyomi-anime-repo#4] opened 2024-06-22 11:02 UTC
![Screenshot_2024-06-22-18-19-14-60_2482a40d039b33a91f6bb85d9ee04835](https://github.com/almightyhak/aniyomi-anime-repo/assets/108851106/700a3932-6908-4da3-b6ed-a840be8c6a4e)

Hianime & Kaido extensions has an error and can't play episodes.

I can still pick episodes from their list but when I play an episode on Hianime & Kaido I get an error as seen in the screenshot.(loading failed: https: HTTP error 521)

These extensions used to work and now for some reason it fails to load. Although now I temporarily use other extensions.

Extensions I tested and the error didn't appear:
-Animeonsen
-Gogoanime
-Animewave
-Allanime
-Kickassanime

**Comment by CircleSideisCOOL** [comment] 2024-06-22 11:27
It works now for some reason, maybe it was a me problem🤣

**Comment by CircleSideisCOOL** [comment] 2024-06-22 11:36
Now the error is back😭 Anyone knows how to fix this?

**Comment by Goplr** [comment] 2024-06-22 12:33
@CircleSideisCOOL

HTTP Error 521 meant the web server (where the video is stored) is down, this could be caused by high demand, etc. That might be why you can sometimes watch the video, and othertimes not

I don't think this can be fixed on the extension side, unfortunately 😅

**Comment by almightyhak** [comment] 2024-06-22 13:18
yeah it's the server i can't do anything to fix it

**Closed by almightyhak** 2024-06-22 13:18 UTC
